/*
 * Generated DTESN Kernel Configuration Header
 * Source: BasicEchoKernel v1.0
 * Generated by: DTESN Kernel Specification Compiler
 */

#ifndef _DTESN_CONFIG_H_
#define _DTESN_CONFIG_H_

/* Configuration Metadata */
#define DTESN_CONFIG_NAME "BasicEchoKernel"
#define DTESN_CONFIG_VERSION "1.0"
#define DTESN_MAX_DEPTH 4

/* Membrane Hierarchy Configuration */
#define DTESN_MEMBRANE_LEVELS 5

typedef struct dtesn_membrane_config {
    uint32_t level;
    uint32_t count;
    uint32_t neurons;
    const char* type;
} dtesn_membrane_config_t;

static const dtesn_membrane_config_t dtesn_membrane_configs[] = {
    { 0, 1, 100, "root" },
    { 1, 1, 200, "trunk" },
    { 2, 1, 150, "branch" },
    { 3, 2, 100, "leaf" },
    { 4, 4, 50, "terminal" },
};

/* ESN Parameters */
#define DTESN_SPECTRAL_RADIUS 0.9f
#define DTESN_INPUT_SCALING 0.1f
#define DTESN_LEAK_RATE 0.3f
#define DTESN_CONNECTIVITY 0.1f

/* Timing Constraints (microseconds/milliseconds) */
#define DTESN_MEMBRANE_EVOLUTION_MAX_US 10
#define DTESN_BSERIES_COMPUTATION_MAX_US 100
#define DTESN_ESN_UPDATE_MAX_MS 1
#define DTESN_CONTEXT_SWITCH_MAX_US 5

/* Memory Layout */
#define DTESN_USER_SPACE_BASE 0x00000000UL
#define DTESN_USER_SPACE_END  0x3FFFFFFFUL
#define DTESN_MEMBRANE_BASE   0x40000000UL
#define DTESN_MEMBRANE_END    0x7FFFFFFFUL
#define DTESN_BSERIES_BASE    0x80000000UL
#define DTESN_BSERIES_END     0xBFFFFFFFUL
#define DTESN_KERNEL_BASE     0xC0000000UL
#define DTESN_KERNEL_END      0xFFFFFFFFUL

#endif /* _DTESN_CONFIG_H_ */
